apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hybrisdb-pv-claim
  namespace: hybris
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
