apiVersion: v1
kind: PersistentVolume
metadata:
  name: ypai-media-pv
spec:
  capacity:
    storage: 1T
  accessModes:
  - ReadWriteMany
  nfs:
    path: /hybris_media
    server: 10.72.102.162
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ypai-media-pvc
spec:
  volumeName: ypai-media-pv
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1T
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeping-pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubeping-k8s-api-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeping-pod-reader
subjects:
- kind: ServiceAccount
  name: hybris-platform-service-account
  namespace: default
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solr
  labels:
    app: solr
spec:
  serviceName: solr
  selector:
    matchLabels:
      app: solr
  replicas: 1
  template:
    metadata:
      labels:
        app: solr
    spec:
      containers:
      - name: solr
        imagePullPolicy: Always
        image: gcr.io/hybris-on-gcp/hybris_solr:stable
        args: ["default"]
        
        ports:
        - containerPort: 8983
          name: solr-client
          protocol: TCP

        volumeMounts:
        - mountPath: /opt/solr/server/solr/cores
          name: solr-pvc
        
        resources:
          requests:
            memory: 2Gi
            cpu: 1
          limits:
            memory: 2Gi
            cpu: 2
        

      restartPolicy: Always

  volumeClaimTemplates:
  - metadata:
      name: solr-pvc
      annotations:
        pv.beta.kubernetes.io/gid: "8983"
    spec:
      accessModes:
        - ReadWriteOnce
        
      resources:
        requests:
          storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: solr
  labels:
    app: solr
spec:
  ports:
  - port: 8983
    name: solr
    protocol: TCP
  selector:
    app: solr